LOOPS IN PYTHON




1.   While Loop
2.   IF Loop



1: Creating an error variable that equals to 50.0, then divide it by 5 and print the variable as long as the it is greater than 1

In [ ]:
error = 50.0
error = error / 5
while error > 1:
 print(error)

Streaming output truncated to the last 5000 lines.
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0
10.0

2: Create a variable offset with an initial value of 8. Code a while loop that keeps running as long as the offset is not equal to 0. Print out the sentence "correcting...".


In [ ]:
offset = 8
while offset != 0:
  print('correcting')
  offset = offset-1
  print(offset)

correcting
7
correcting
6
correcting
5
correcting
4
correcting
3
correcting
2
correcting
1
correcting
0


**IF & ELSE WITHIN WHILE LOOP**

4:Creating an error variable that equals to 40, if error equals to 10 divide error by 2, else divide error by 4 as long as error is greater than 0.

In [ ]:
error = 40
while error > 0:
  if error == 10:
    error = error/2
    print(error)
  else:
    error = error/4
    print(error)

10.0
5.0
1.25
0.3125
0.078125
0.01953125
0.0048828125
0.001220703125
0.00030517578125
7.62939453125e-05
1.9073486328125e-05
4.76837158203125e-06
1.1920928955078125e-06
2.980232238769531e-07
7.450580596923828e-08
1.862645149230957e-08
4.6566128730773926e-09
1.1641532182693481e-09
2.9103830456733704e-10
7.275957614183426e-11
1.8189894035458565e-11
4.547473508864641e-12
1.1368683772161603e-12
2.8421709430404007e-13
7.105427357601002e-14
1.7763568394002505e-14
4.440892098500626e-15
1.1102230246251565e-15
2.7755575615628914e-16
6.938893903907228e-17
1.734723475976807e-17
4.336808689942018e-18
1.0842021724855044e-18
2.710505431213761e-19
6.776263578034403e-20
1.6940658945086007e-20
4.235164736271502e-21
1.0587911840678754e-21
2.6469779601696886e-22
6.617444900424221e-23
1.6543612251060553e-23
4.1359030627651384e-24
1.0339757656912846e-24
2.5849394142282115e-25
6.462348535570529e-26
1.6155871338926322e-26
4.0389678347315804e-27
1.0097419586828951e-27
2.524354896707238e-28
6.310887241768094e-2

5: In the last task we created a variable offset, the while loop that corrects the offset is a good start, but
what if the offset is negative?

Write a code where offset is initialized to -6.


In [ ]:
offset = -6
while offset != 0:
  print('correcting')
  offset = offset-1
  print(offset)

Streaming output truncated to the last 5000 lines.
correcting
-109418799
correcting
-109418800
correcting
-109418801
correcting
-109418802
correcting
-109418803
correcting
-109418804
correcting
-109418805
correcting
-109418806
correcting
-109418807
correcting
-109418808
correcting
-109418809
correcting
-109418810
correcting
-109418811
correcting
-109418812
correcting
-109418813
correcting
-109418814
correcting
-109418815
correcting
-109418816
correcting
-109418817
correcting
-109418818
correcting
-109418819
correcting
-109418820
correcting
-109418821
correcting
-109418822
correcting
-109418823
correcting
-109418824
correcting
-109418825
correcting
-109418826
correcting
-109418827
correcting
-109418828
correcting
-109418829
correcting
-109418830
correcting
-109418831
correcting
-109418832
correcting
-109418833
correcting
-109418834
correcting
-109418835
correcting
-109418836
correcting
-109418837
correcting
-109418838
correcting
-109418839
correcting
-109418840
correcting
-109418841
cor

Fix things by putting an if-else statement inside the while loop.
If offset is greater than zero, you should decrease offset by 1. Else, you should
increase offset by 1.

**Note:** If your code is still taking too long to run (or your session is expiring), you probably made a mistake. Check your code and make sure
that the statement offset != 0 will eventually evaluate to FALSE!


In [ ]:
offset = -6
 # Coding the while loop
while offset != 0 :
  print("correcting...")
  if offset>0 :
    offset=offset-1
  else :
    offset=offset+1
    print(offset)

**FOR LOOP**

The for statement is used to iterate over the elements of a sequence.

◼ It's used when you have a piece of code which you want to repeat n number of time.

◼ The for loop is often distinguished by an explicit loop counter or loop variable.

◼ For loops are used for sequential traversal. For example: traversing a list or string or array etc.


**LOOP Over a LIST**
1:Using a for loop that iterates over all the values in height of the fam list and prints out every element

Write a for loop that iterates over all elements of the areas list and prints out every element separately.
Use the following code to solve this task:

# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]


In [ ]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
for area in areas:
  print(area)

11.25
18.0
20.0
10.75
9.5


**LOOP OVER INDEXES AND VALUES**

Using a for loop print the detail of the areas list so that your result looks like "room x: y". Where x is the index of the
list element & y is the area.
Use the following code to solve this task:

areas = [11.25, 18.0, 20.0, 10.75, 9.50]


In [ ]:
fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam) :
  print("person " + str(index) + ": " + str(height))

person 0: 1.73
person 1: 1.68
person 2: 1.71
person 3: 1.89


In [ ]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
for index, height in enumerate(areas) :
  print("room " + str(index) + ": " + str(height))

room 0: 11.25
room 1: 18.0
room 2: 20.0
room 3: 10.75
room 4: 9.5


2: Use the print() function in the for loop so that the first printout becomes
"room 1: 11.25", the second one "room 2: 18.0" and so on

In [ ]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
for index, height in enumerate(areas) :
  print("room " + str(index+1) + ": " + str(height))

room 1: 11.25
room 2: 18.0
room 3: 20.0
room 4: 10.75
room 5: 9.5


**LOOP OVER DICTIONARY**

statesandcapitals={'Alabama':'Montgomery','Alaska':'Juneau','Arizona':'Phoenix','Arkansas': 'Little Rock'}

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
'austria':'vienna'}

1:Write a for loop that goes through each key:value pair of europe.
On each iteration, "the capital of x is y" should be printed out, where x is the key and y is the value of the pair.

Use the europe dictionary to complete this task.
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo', 'italy':'rome', 'poland':'warsaw', 'austria':'vienna'}


In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
'austria':'vienna'}

for country, capital in europe.items:
  print("room " + str(index+1) + ": " + str(height))

In [ ]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
'austria':'vienna'}

for country, capital in europe.items():
  print("the capital of " + str(country) + " is " + str(capital))

the capital of spain is madrid
the capital of france is paris
the capital of germany is berlin
the capital of norway is oslo
the capital of italy is rome
the capital of poland is warsaw
the capital of austria is vienna


**LOOP OVER A 1D NUMPY ARRAY**

If you're dealing with a 1D Numpy array, looping over all elements can be as simple as:


**LOOP OVER A 2D NUMPY ARRAY**

for x in np.nditer(my_array)

In [ ]:
import numpy  as np
 #creating an array
array=[0, 1, 2, 3 ,4, 5, 6, 7, 8, 9, 10, 11]
#adding a for loop
np_array=np.array(array)
for x in np_array:
  print(x)

0
1
2
3
4
5
6
7
8
9
10
11


Two Numpy arrays that you might recognize from the previous classes:

◼ np_height, a Numpy array containing the heights of Major League Baseball players

◼ np_baseball, a 2D Numpy array that contains both the heights (first column) and weights (second column)
of those players.

This data is loaded onto github
https://raw.githubusercontent.com/Masadn/PythonCourse/master/dataset/baseball_height_weight.csv


In [ ]:
array = [[0,1],[2,3],[4,5],[6,7]]
np_array = np.array(array)
for x in np.nditer(np_array):
  print(x)

0
1
2
3
4
5
6
7


In [ ]:
# array = [[0,1],[2,3],[4,5],[6,7]]
np_array = np.array([[0,1],[2,3]])
for x in (np_array):
  print(x)

[0 1]
[2 3]


1: Write a for loop that iterates over all elements in np_height and prints out "x inches" for each element, where x is the
value in the array. Use the following data to create a 1D Numpy array from the height column

In [30]:
import pandas as pd
import numpy as np
array =pd.read_csv("https://raw.githubusercontent.com/Masadn/PythonCourse/master/dataset/baseball_height_weight.csv")
np_array =np.array(array)
np_array

array([[ 74., 215.],
       [ 72., 210.],
       [ 72., 210.],
       ...,
       [ 77., 210.],
       [ 79., 205.],
       [ 78., 208.]])

In [29]:
for x in np_array:
  print( x)

[ 74. 215.]
[ 72. 210.]
[ 72. 210.]
[ 73. 188.]
[ 69. 176.]
[ 69. 209.]
[ 71. 200.]
[ 76. 231.]
[ 71. 180.]
[ 73. 188.]
[ 73. 180.]
[ 74. 185.]
[ 74. 160.]
[ 69. 180.]
[ 70. 185.]
[ 73. 189.]
[ 75. 185.]
[ 78. 219.]
[ 79. 230.]
[ 76. 205.]
[ 74. 230.]
[ 76. 195.]
[ 72. 180.]
[ 71. 192.]
[ 75. 225.]
[ 77. 203.]
[ 74. 195.]
[ 73. 182.]
[ 74. 188.]
[ 78. 200.]
[ 73. 180.]
[ 75. 200.]
[ 73. 200.]
[ 75. 245.]
[ 75. 240.]
[ 74. 215.]
[ 69. 185.]
[ 71. 175.]
[ 74. 199.]
[ 73. 200.]
[ 73. 215.]
[ 76. 200.]
[ 74. 205.]
[ 74. 206.]
[ 70. 186.]
[ 72. 188.]
[ 77. 220.]
[ 74. 210.]
[ 70. 195.]
[ 73. 200.]
[ 75. 200.]
[ 76. 212.]
[ 76. 224.]
[ 78. 210.]
[ 74. 205.]
[ 74. 220.]
[ 76. 195.]
[ 77. 200.]
[ 81. 260.]
[ 78. 228.]
[ 75. 270.]
[ 77. 200.]
[ 75. 210.]
[ 76. 190.]
[ 74. 220.]
[ 72. 180.]
[ 72. 205.]
[ 75. 210.]
[ 73. 220.]
[ 73. 211.]
[ 73. 200.]
[ 70. 180.]
[ 70. 190.]
[ 70. 170.]
[ 76. 230.]
[ 68. 155.]
[ 71. 185.]
[ 72. 185.]
[ 75. 200.]
[ 75. 225.]
[ 75. 225.]
[ 75. 220.]
[ 68. 160.]
[ 74

2: Write a for loop that visits every element of the np_baseball array and prints it out.


**LOOP OVER A DATAFRAME**

Syntax:
for lab, row in dataframe.iterrows() :
print(lab,row)


Name,Team,Number,Position,Age,Height,Weight,College,Salary
Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,,5000000.0
Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,,12000000.0
Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0

Write a for loop that iterates over the rows on the cars dataset and print out the row label and the rows contents.
#cars data
https://raw.githubusercontent.com/Masadn/PythonCourse/master/dataset/cars.csv


In [2]:
import pandas as pd
import numpy as np

data = pd.read_csv("https://raw.githubusercontent.com/Masadn/PythonCourse/master/dataset/nba.csv")

for index, row in data.iterrows():
   print(index, row)

0 Name         Avery Bradley
Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: 0, dtype: object
1 Name           Jae Crowder
Team        Boston Celtics
Number                99.0
Position                SF
Age                   25.0
Height                 6-6
Weight               235.0
College          Marquette
Salary           6796117.0
Name: 1, dtype: object
2 Name             John Holland
Team           Boston Celtics
Number                   30.0
Position                   SG
Age                      27.0
Height                    6-5
Weight                  205.0
College     Boston University
Salary                    NaN
Name: 2, dtype: object
3 Name           R.J. Hunter
Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weigh

The row data that's generated by iterrows() on every run is a Pandas Series.
This format is not very convenient to print out. Luckily, you can easily select variables from the Pandas Series using square brackets:
Syntax: for index, row in dataframe.iterrows() :
print(row['column'])

1:In the cars dataset using the iterators index and row, adapt the code in the for loop such
that the first iteration prints out "US: 809", the second iteration "AUS: 731", and so on.

In [7]:
import pandas as pd
import numpy as np

data = pd.read_csv("https://raw.githubusercontent.com/Masadn/PythonCourse/master/dataset/cars.csv")

data

Unnamed: 0  cars_per_cap        country  drives_right
0         US           809  United States          True
1        AUS           731      Australia         False
2        JAP           588          Japan         False
3         IN            18          India         False
4         RU           200         Russia          True
5        MOR            70        Morocco          True
6         EG            45          Egypt          True

In [18]:
import pandas as pd
import numpy as np

data = pd.read_csv("https://raw.githubusercontent.com/Masadn/PythonCourse/master/dataset/cars.csv")

# Loop using iterrows
for index, row in data.iterrows():
    print(f"{row['Unnamed: 0']}: {row['cars_per_cap']}")

US: 809
AUS: 731
JAP: 588
IN: 18
RU: 200
MOR: 70
EG: 45


You can add a new column for length of the country names of the cars DataFrame by using the for loop

In [20]:
data['country_length'] = [len(country) for country in data['country']]

data

Unnamed: 0  cars_per_cap        country  drives_right  country_length
0         US           809  United States          True              13
1        AUS           731      Australia         False               9
2        JAP           588          Japan         False               5
3         IN            18          India         False               5
4         RU           200         Russia          True               6
5        MOR            70        Morocco          True               7
6         EG            45          Egypt          True               5

2:Add a new column, named “COUNTRY”, that contains a uppercase version of the
country names in the "country" column

In [21]:
data['COUNTRY'] = data['country'].str.upper()
print(data)

  Unnamed: 0  cars_per_cap        country  drives_right  country_length  \
0         US           809  United States          True              13   
1        AUS           731      Australia         False               9   
2        JAP           588          Japan         False               5   
3         IN            18          India         False               5   
4         RU           200         Russia          True               6   
5        MOR            70        Morocco          True               7   
6         EG            45          Egypt          True               5   

         COUNTRY  
0  UNITED STATES  
1      AUSTRALIA  
2          JAPAN  
3          INDIA  
4         RUSSIA  
5        MOROCCO  
6          EGYPT  


3:Using a for loop add a new column, named “Drives”, that contains the values drives “right” or “left”

In [15]:
drives = []


for index, row in data.iterrows():
    if row['drives_right']:
        drives.append('right')
    else:
        drives.append('left')

data['Drives'] = drives

data

Unnamed: 0  cars_per_cap        country  drives_right        COUNTRY Drives
0         US           809  United States          True  UNITED STATES  right
1        AUS           731      Australia         False      AUSTRALIA   left
2        JAP           588          Japan         False          JAPAN   left
3         IN            18          India         False          INDIA   left
4         RU           200         Russia          True         RUSSIA  right
5        MOR            70        Morocco          True        MOROCCO  right
6         EG            45          Egypt          True          EGYPT  right

**Exercise: Analyze Employees' Work Hours**

Dataset:

You have a list of employees and their work hours for a week:

employees = ["Alice", "Bob", "Charlie", "David", "Eva"]

work_hours = [35, 45, 50, 20, 40]

Tasks:
Use a for loop to iterate through the list of employees and their work hours.

If an employee works 40 hours or more, they qualify for overtime. Otherwise, they do not.

Add a simple "Overtime" status (Yes/No) for each employee.

Count how many employees qualify for overtime.

Print the final results.

Use a for loop to iterate through the list of employees and their work hours.

In [1]:
employees = ["Alice", "Bob", "Charlie", "David", "Eva"]

work_hours = [35, 45, 50, 20, 40]

for i in employees, work_hours :
  print(i)


['Alice', 'Bob', 'Charlie', 'David', 'Eva']
[35, 45, 50, 20, 40]


If an employee works 40 hours or more, they qualify for overtime. Otherwise, they do not.

Add a simple "Overtime" status (Yes/No) for each employee.

In [15]:
overtime_status = []
overtime_count = 0

for i in range(len(employees)):
  if work_hours[i] > 40:
    overtime_status.append("Yes")
    overtime_count += 1
  else:
    overtime_status.append("No")


print("Employee\tWork Hours\tOvertime")
for i in range(len(employees)):
  print(f"{employees[i]}\t{work_hours[i]}\t\t{overtime_status[i]}")

print(f"\nNumber of employees qualified for overtime: {overtime_count}")

Employee	Work Hours	Overtime
Alice	35		No
Bob	45		Yes
Charlie	50		Yes
David	20		No
Eva	40		No

Number of employees qualified for overtime: 2
